# Testing profile
# docker compose -f docker-compose.yml -f docker-compose.test.yml up --build
# You only need to include the services you are changing in the override file.
# All other settings will be inherited from the original docker-compose.yml file.
# Project name
name: cba

services:
  account-service:
    extends:
      file: docker-compose.yml
      service: account-service
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: # Important: In a production environment you should remove the external port that kept here for debugging purposes.
      - ${ACCOUNT_SRV_PORT}:5000 # external port / container port
    env_file:
      - .env.testing
    deploy:
      replicas: 1
