# This task runs Flake8 linting on the provided source code.
#
# This task mounts the specified workspace containing the source code and
# runs Flake8 to check for style and syntax issues.  The `args` parameter
# can be used to pass additional arguments to Flake8.
apiVersion: tekton.dev/v1beta1 # Tekton API version
kind: Task
metadata:
  name: run-flake8-lint # Name of the task
  labels:
    app: cba-pipeline
    environment: development
    team: devops
spec:
  description: This task will run Flake8 linting on the provided source code.
  workspaces:
    - name: source
      description: The workspace containing the source code to lint.
      mountPath: /workspace
  params:
    - name: args
      description: Arguments to pass to Flake8 (optional).
      type: array
      default: [ "--count", "--max-complexity=10", "--max-line-length=127", "--statistics" ]
  steps:
    - name: lint
      image: python:3.9-slim-bullseye
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -euo pipefail # Ensure that a pipeline fails if any command in the pipeline fails
        
        echo "Installing Flake8..." 
        
        pip install --no-cache-dir flake8 
        
        echo "Running Flake8 linting..."
        
        flake8 "${params.args[@]}"
        
        # Capture and display linting results
        lint_result=$?  # Capture the exit code
        
        if [[ $lint_result -eq 0 ]]; then
          echo "Flake8 linting PASSED."
        else
          echo "Flake8 linting FAILED. Check the output for details."
          exit $lint_result  # Fail the Task if linting fails
        fi
        
        echo "Linting completed."
