name: Continuous Delivery (CD)

# An event that triggers a workflow run
on:
  # Trigger the workflow manually,
  workflow_dispatch:

jobs:
  build-and-deliver:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for pushing tags

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main  # Explicitly checkout the main branch
          fetch-depth: 0 # Fetch all history for tagging

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.11.2-rootless

      - name: Login to Docker Hub
        id: docker-login
        uses: docker/login-action@v2
        with:
          registry: docker.io  # Default Docker Hub registry
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: build-push
        if: steps.docker-login.outcome == 'success'
        uses: docker/build-push-action@v3
        with:
          context: .  # Build context is the root of the repo
          file: Dockerfile # Path to Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_REPO_NAME }}:v${{ github.run_number }}
          build-args: |
            VERSION=${{ github.sha }}

      - name: Create Git tag
        if: steps.build-push.outcome == 'success'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if git tag -l v${{ github.run_number }}; then
            echo "Tag v${{ github.run_number }} already exists. Skipping."
          else
            git tag v${{ github.run_number }} -a -m "Release v${{ github.run_number }} - Built from commit ${{ github.sha }}"
            git push origin v${{ github.run_number }}
          fi

#      - name: Create GitHub Release (Recommended)
#        if: steps.build-push.outcome == 'success'
#        uses: actions/create-release@v1
#        with:
#          tag_name: v${{ github.run_number }}
#          release_name: Release v${{ github.run_number }}
#          body: |
#            Automated release from GitHub Actions.
#            Commit SHA: ${{ github.sha }}
